version: '3.3'

services:

  localstack:
    image: localstack/localstack:0.11.6
    ports:
      - '4566:4566'
      - '8055:8080'
    environment:
      SERVICES: s3
      DEBUG: 1
      DATA_DIR: "/tmp/localstack/data"
      AWS_ACCESS_KEY_ID: "1234"
      AWS_SECRET_ACCESS_KEY: "1234"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_REGION: "us-east-1"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    tmpfs:
      - '/tmp/localstack:exec,mode=600'    #allow access to localstack to the temp folder
                                           #to clean it up after tests are run